[env:esp32c3]
platform = espressif32
board = lolin_c3_mini
framework = arduino
monitor_speed = 115200
build_flags =
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DBOARD_ESP32C3

[env:rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
lib_deps = adafruit/Adafruit NeoPixel@^1.12.0
build_flags = -DBOARD_RP2040
upload_protocol = picotool
